/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;


import com.itextpdf.xmp.XMPMetaFactory;
import com.mysql.cj.protocol.Resultset;
import javax.swing.table.DefaultTableModel;
import model.MySQL;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Oshadha
 */
public class wproductTable extends javax.swing.JDialog {
    
    private static HashMap<String, String> categoryMap = new HashMap<>();

    /**
     * Creates new form productTable
     */
    public wproductTable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadWProducts();
        loadCategory();
    }
    
   private void loadWProducts(){
        
        
        try {
            
            ResultSet resultset = MySQL.executeSearch("SELECT * FROM `w_product`"
                    + "INNER JOIN `category` ON `w_product`.`category_id` = `category`.`id`");
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            
            while (resultset.next()) {

                Vector<String> vector = new Vector<>();
                vector.add(resultset.getString("id"));
                vector.add(resultset.getString("name"));
                vector.add(resultset.getString("price"));
                vector.add(resultset.getString("weight"));
                vector.add(resultset.getString("category.name"));
                model.addRow(vector);
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
   
   private void loadCategory (){
       
       try {
           ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `category`");
           
           Vector<String> vector = new Vector<>();
           vector.add("Select");
           
           while (resultSet.next()) {
           vector.add(resultSet.getString("name"));
           categoryMap.put(resultSet.getString("name"), resultSet.getString("id"));
           
               
           }
           DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
           jComboBox1.setModel(model);
           
           
       } catch (Exception e) {
           e.printStackTrace();
       }
   }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product Table");
        setBackground(new java.awt.Color(245, 219, 200));

        jPanel1.setBackground(new java.awt.Color(245, 219, 200));
        jPanel1.setForeground(new java.awt.Color(245, 219, 200));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(245, 219, 200));

        jTable1.setBackground(new java.awt.Color(255, 246, 209));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Price", "Weight", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Product Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 190, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 190, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Category");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 63, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 190, 30));

        jButton1.setBackground(new java.awt.Color(255, 246, 209));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 130, 30));

        jButton2.setBackground(new java.awt.Color(255, 246, 209));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 130, 30));

        jButton3.setBackground(new java.awt.Color(255, 246, 209));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Price");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 190, 20));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 190, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Weight");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 190, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 190, 30));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String pname = jTextField1.getText();
            
            MySQL.executeIUD("DELETE FROM `w_product` "
                    + "WHERE `name` = '"+pname+"'");
        } catch (Exception e) {
            e.printStackTrace();
        }
        loadWProducts();
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            String pname = jTextField1.getText();
            String price = jTextField2.getText();
            String weight = jTextField3.getText();
            String category = String.valueOf(jComboBox1.getSelectedItem());
            
            if (pname.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Product Name","Warning",JOptionPane.WARNING_MESSAGE);
            }else if (price.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Price","Warning", JOptionPane.WARNING_MESSAGE);
            }else if (weight.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Weight","Warning",JOptionPane.WARNING_MESSAGE);

            }else if (category.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Category","Warning",JOptionPane.WARNING_MESSAGE);
               
            }else {
                ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `w_product` WHERE `name`='"+pname+"'");
                
                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, "This product already Registeres","Warning", JOptionPane.WARNING_MESSAGE);
                    
                } else {
                    MySQL.executeIUD("INSERT INTO `w_product`(`name`,`price`,`weight`,`category_id`)"
                            + "VALUES ('"+pname+"','"+price+"','"+weight+"',"
                                    + "'"+categoryMap.get(category)+"')");
                    JOptionPane.showMessageDialog(this, "New Product added","Warning",JOptionPane.INFORMATION_MESSAGE);
                    loadWProducts();
                    reset();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            String pname = jTextField1.getText();
            String price = jTextField2.getText();
            String weight = jTextField3.getText();
            String category = String.valueOf(jComboBox1.getSelectedItem());
            
            if (pname.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Product Name","Warning",JOptionPane.WARNING_MESSAGE);
            }else if (price.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Price","Warning", JOptionPane.WARNING_MESSAGE);
            }else if (weight.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Weight","Warning",JOptionPane.WARNING_MESSAGE);

            }else if (category.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Category","Warning",JOptionPane.WARNING_MESSAGE);
               
            }else {
                ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `w_product` WHERE `name`='"+pname+"'");
                
                boolean canUpdate = false;
                
                if (resultSet.next()) {
                    if (!resultSet.getString("name").equals(pname)) {
                        JOptionPane.showMessageDialog(this, "This product already used","Warning",JOptionPane.WARNING_MESSAGE);
                        
                    } else {
                        canUpdate = true;
                    }
                    
                    }else {
                            canUpdate = true;
                    } if (canUpdate) {
                        String updateQuery = "UPDATE w_product SET "
                                + "name = '"+pname+"',"
                                + "price = '"+price+"',"
                                + "weight = '"+weight+"',"
                                + "category_id = '"+categoryMap.get(category)+"'";
                                MySQL.executeIUD(updateQuery);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Product Updated","Warning",JOptionPane.INFORMATION_MESSAGE);
                    loadWProducts();
                    reset();
                   
                }
               
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                jLabel5.setText(String.valueOf(jTable1.getValueAt(selectedRow, 0)));
                jTextField1.setText(String.valueOf(jTable1.getValueAt(selectedRow, 1)));
                jTextField2.setText(String.valueOf(jTable1.getValueAt(selectedRow, 2)));
                jTextField3.setText(String.valueOf(jTable1.getValueAt(selectedRow, 3)));
                jComboBox1.setSelectedItem(String.valueOf(jTable1.getValueAt(selectedRow, 4)));
                
            }
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wproductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wproductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wproductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wproductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                wproductTable dialog = new wproductTable(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedItem("Select");
    }
}
